#!/bin/bash
#
# Test suite for NM dispatch scripts
#

function usage() {
  echo "Usage: ${0##*/} ddns [<interface>]"
  echo "Usage: ${0##*/} <interface> <action> [<script-prefix>]"
  exit 1
}

if [ -z "$1" ]; then
  usage
elif [ -z "$2" -a "$1" != "ddns" ]; then
  usage
fi

# never syslog on tests
export nmg_log_stderr=1

#export nmg_dryrun=0
export nmg_show_debug=1

# override defaults
export NMUTILS="../etc/nmutils"
export NMCONF="conf"

# uncomment to test against fake "running" dhclient
#dhclient_test -pf "$RUNDIR/dhclient-ipv6-prefix-$1.pid" sleep && sleep 1

if [ "$1" = "ddns" ]; then
  ../sbin/nmddns-helper "${2:-}"
else
  for script in ../etc/NetworkManager/dispatcher.d/$3*; do
    "$script" "$1" "$2"
  done
fi

