#!/bin/bash
#
# Test suite for NM dispatch scripts
#

# if desired, export nmg_show_debug as we use in some test programs
#export nmg_show_debug=1

fail() {
  echo >&2 "$*"
  exit 1
}

# load common.sh
TEST_COMMON=${TEST_COMMON:-conf/common.sh}
[ -r "$TEST_COMMON" ] && . "$TEST_COMMON" || fail "Unable to load common.sh"

function usage() {
  echo "Usage: ${0##*/} ddns [<interface>]"
  echo "Usage: ${0##*/} <interface> <action> [<script-prefix>]"
  exit 1
}

if [ -z "$1" ]; then
  usage
elif [ -z "$2" -a "$1" != "ddns" ]; then
  usage
fi

# uncomment to test against fake "running" dhclient
#dhclient_test -pf "$RUNDIR/dhclient-ipv6-prefix-$1.pid" sleep && sleep 1

if [ "$1" = "ddns" ]; then
  bash "$SRC_ROOT/sbin/nmddns-helper" "${2:-}"
else
  for script in "$SRC_ROOT/etc/NetworkManager/dispatcher.d/$3"*; do
    bash "$script" "$1" "$2"
  done
fi

