#!/bin/bash
#
# Fake radvd to test scripts
#
# Set the following in your radvd-gen.conf file to test:
#

[ "$1" = "-h" ] && {
  echo "Usage: ${0##*/} [ <radvd-gen-args> ]"
  exit 1
}

# sane defaults
export SRC_ROOT=${SRC_ROOT-..}
export RADVDGEN_CONF=${RADVDGEN_CONF-conf/radvd-gen.conf}

bash "$SRC_ROOT/etc/NetworkManager/dispatcher.d/95-radvd-gen" "$@" eth0 up

